// SPDX-FileCopyrightText: 2025-2026 Uncore <https://github.com/uncor3>
// SPDX-License-Identifier: AGPL-3.0-or-later

use qmetaobject::qrc;

qrc!(pub rsrc,
    "/" {
        "resources/icons/bxs_terminal.svg",
        "resources/icons/clarity_eye-hide-line.svg",
        "resources/icons/clarity_eye-line.svg",
        "resources/icons/clarity_hard-disk-solid-alerted.svg",
        "resources/icons/fluent_filmstrip-play-20-regular.svg",
        "resources/icons/globe_network.svg",
        "resources/icons/hugeicons_wrench-01.svg",
        "resources/icons/idescriptor-battery-details.svg",
        "resources/icons/idescriptor-unpair.svg",
        "resources/icons/plain-icon.svg",
        "resources/icons/ic_baseline-insert-drive-file.svg",
        "resources/icons/ic_outline-power-settings-new.svg",
        "resources/icons/ic_outline-refresh.svg",
        "resources/icons/ic_twotone-restart-alt.svg",
        "resources/icons/icon-park-outline_more-two.svg",
        "resources/icons/ipad_gen1.svg",
        "resources/icons/ipad_gen1_placeholder.png",
        "resources/icons/ipad_gen2.svg",
        "resources/icons/ipad_gen2_placeholder.png",
        "resources/icons/iphone_gen1.svg",
        "resources/icons/iphone_gen1_placeholder.png",
        "resources/icons/iphone_gen2.svg",
        "resources/icons/iphone_gen2_placeholder.png",
        "resources/icons/iphone_gen3.svg",
        "resources/icons/iphone_gen3_placeholder.png",
        "resources/icons/lets-icons_import.svg",
        "resources/icons/lets-icons_horizontal-down-left-main-light.svg",
        "resources/icons/material-symbols_airplay-outline-rounded.svg",
        "resources/icons/material-symbols_android-wifi-3-bar-plus.svg",
        "resources/icons/material-symbols_arrow-left-alt.svg",
        "resources/icons/material-symbols_arrow-right-alt.svg",
        "resources/icons/material-symbols_arrow-upward-rounded.svg",
        "resources/icons/material-symbols_cable-rounded.svg",
        "resources/icons/material-symbols_close-rounded.svg",
        "resources/icons/material-symbols_delete.svg",
        "resources/icons/material-symbols_favorite.svg",
        "resources/icons/material-symbols_folder.svg",
        "resources/icons/material-symbols_home.svg",
        "resources/icons/material-symbols_image-outline-sharp.svg",
        "resources/icons/material-symbols_keyboard-arrow-down.svg",
        "resources/icons/material-symbols_keyboard-arrow-up.svg",
        "resources/icons/material-symbols_keyboard-return.svg",
        "resources/icons/material-symbols_location-on-outline.svg",
        "resources/icons/material-symbols_info-outline.svg",
        "resources/icons/material-symbols_rotate-right.svg",
        "resources/icons/material-symbols_volume-mute.svg",
        "resources/icons/material-symbols_volume-off.svg",
        "resources/icons/mdi_disk.svg",
        "resources/icons/mdi_github.svg",
        "resources/icons/mdi_lightning-bolt.svg",
        "resources/icons/mdi_magnify.svg",
        "resources/icons/mdi_magnify-minus.svg",
        "resources/icons/mdi_magnify-plus.svg",
        "resources/icons/mingcute_settings-7-line.svg",
        "resources/icons/pepicons-print_cellphone-eye.svg",
        "resources/icons/ph_export.svg",
        "resources/icons/qlementine-icons_wireless-1-16.svg",
        "resources/icons/sidebar_app_store.svg",
        "resources/icons/sidebar_apps.svg",
        "resources/icons/sidebar_files.svg",
        "resources/icons/sidebar_gallery.svg",
        "resources/icons/sidebar_info.svg",
        "resources/icons/sidebar_jailbroken.svg",
        "resources/icons/sidebar_left.svg",
        "resources/icons/sidebar_toolbox.svg",
        "resources/icons/simple-icons_opencollective.svg",
        "resources/icons/simple-icons_linkedin.svg",
        "resources/icons/simple-icons_reddit.svg",
        "resources/icons/streamline-freehand_charging-flash-wireless.svg",
        "resources/icons/streamline_programming-browser-search-search-window-glass-app-code-programming-query-find-magnifying-apps.svg",
        "resources/icons/streamline_ultimate-multiple-users-network.svg",
        "resources/icons/tabler_database-export.svg",
        "resources/icons/uim_process.svg",
        "resources/icons/fuse.svg",
        "packaging/shared/resources/app-icon/icon.png",
        "resources/icons/mi_options-vertical.svg",
        "resources/iphone.png",
        "resources/local-network-consent.png",
        "resources/ios-version.png",
        "resources/ios-wallpapers/iphone-ios4.png",
        "resources/ios-wallpapers/iphone-ios5.png",
        "resources/ios-wallpapers/iphone-ios6.png",
        "resources/ios-wallpapers/iphone-ios7.png",
        "resources/ios-wallpapers/iphone-ios8.png",
        "resources/ios-wallpapers/iphone-ios9.png",
        "resources/ios-wallpapers/iphone-ios10.png",
        "resources/ios-wallpapers/iphone-ios11.png",
        "resources/ios-wallpapers/iphone-ios12.png",
        "resources/ios-wallpapers/iphone-ios13.png",
        "resources/ios-wallpapers/iphone-ios14.png",
        "resources/ios-wallpapers/iphone-ios15.png",
        "resources/ios-wallpapers/iphone-ios16.png",
        "resources/ios-wallpapers/iphone-ios17.png",
        "resources/ios-wallpapers/iphone-ios18.png",
        "resources/ios-wallpapers/iphone-ios26.png",
        "resources/ios-wallpapers/iphone-ios27.jpg",
        "resources/iphone-mockups/iphone-3.png",
        "resources/iphone-mockups/iphone-4.png",
        "resources/iphone-mockups/iphone-5.png",
        "resources/iphone-mockups/iphone-6.png",
        "resources/iphone-mockups/iphone-x.png",
        "resources/iphone-mockups/iphone-15.png",
        "resources/iphone-mockups/iphone-16.png",
        "resources/connect.png",
        "resources/welcome-connect.png",
        "resources/airplay-tutorial.mp4",
        "resources/ipad-mockups/ipad.png",
        "DeveloperDiskImages.json",
        "resources/wireless-gallery-import.mp4",
        "resources/dev-mode.mp4",
        "resources/unlock.mp4",
        "resources/trust.png",

        // ------- Translations --------
        "translations/de.qm",
        "translations/zh_CN.qm",
        "translations/zh_TW.qm",

    }
);

#[cfg(target_os = "macos")]
qrc!(pub macos_rsrc,
    "/" {
        "resources/keychain.mp4",
        "packaging/shared/resources/app-icon/icon.icns",
    }
);
